# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
    - sh -c 'go run . man | gzip -c >./manpages/{{ .ProjectName }}.1.gz'

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

archives:
  - format_overrides:
      - goos: windows
        formats: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }}{{ end }})"